### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by BrainBlasted** [flathub/org.tabos.banking#4]
The latest version of Banking doesn't want to start here.

Here's the log:

```
chris:~/ $ flatpak run org.tabos.banking                             [16:12:29]
Traceback (most recent call last):
  File "/app/bin/banking", line 83, in <module>
    sys.exit(main())
  File "/app/bin/banking", line 77, in main
    return run_application()
  File "/app/bin/banking", line 64, in run_application
    from banking.application import Application
  File "/app/lib/python3.9/site-packages/banking/application.py", line 25, in <module>
    from banking.backend import BankingBackend
  File "/app/lib/python3.9/site-packages/banking/backend.py", line 31, in <module>
    from cryptography.fernet import Fernet
  File "/app/lib/python3.9/site-packages/cryptography/fernet.py", line 18, in <module>
    from cryptography.hazmat.primitives import hashes, padding
  File "/app/lib/python3.9/site-packages/cryptography/hazmat/primitives/padding.py", line 13, in <module>
    from cryptography.hazmat.bindings._padding import lib
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._padding'
```

**Comment by janbrummer** [comment]
That's https://gitlab.com/tabos/banking/-/issues/27
